# fly.toml app configuration file generated for lhc-joker-bot on 2023-09-27T16:56:35-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lhc-joker-bot"
primary_region = "gru"

[build]

[processes]
  worker = "python run.py"
