name: flyio deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: main deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLYIO_API_TOKEN }}